### ISSUE TITLE
where is MQTTS config parameters for TLS/SSL gateway configuration ?  

### ISSUE THREAD

**Issue by gboolt** [AprilBrother/gw4-config-tool#7]

**Comment by volca** [comment]
Please check the firmware version of gateway. The MQTTS option is only available for version >= 1.4.x

**Comment by gboolt** [comment]
Yes my gateway's firmware is 1.4.9

**Comment by gboolt** [comment]
my problem is in the gateway config tool, I cannot find the SSL/TLS configuration fields (loading certificates etc.)

**Comment by volca** [comment]
Please [download latest config tool](https://github.com/AprilBrother/gw4-config-tool/releases) and check again

**Comment by gboolt** [comment]
thanks I was not updated indeed !
