### ISSUE TITLE
MQTTS Setup Certificate Issues 

### ISSUE THREAD

**Issue by gboolt** [AprilBrother/gw4-config-tool#8]
Hi,

I have a self-signed x509 SSL/TLS certificate that I tested with MQTTBox and is working, I tried to copy the data from the certificates files CA (Server), Client & Client Key in the "Setup Certificate" config box but it seems not to be working, and my Key is deleted when I open again the "Setup Certificate" config box. 

Also, why are the header ----BEGIN CERTIFICATE----/----END CERTIFICATE---- present in the Clien Key tab and not ----BEGIN PRIVATE KEY----/-----END PRIVATE KEY ? 

![image](https://user-images.githubusercontent.com/43132835/110293630-1ddf0b00-7fef-11eb-9b21-7af6bf736fc1.png)

**Comment by volca** [comment]
> Also, why are the header ----BEGIN CERTIFICATE----/----END CERTIFICATE---- present in the Clien Key tab and not ----BEGIN PRIVATE KEY----/-----END PRIVATE KEY ?

It should be a bug about the config tool. We'll fix the text soon.

Questions:

* What version of config tool did you use? 
*  the firmware version of gateway?

**Comment by gboolt** [comment]
Ok, it is just the text ? It should still be working by copy/pasting my Client Key ?

- version config tool : 1.3.2.0
- firmware version : 1.4.9

**Comment by volca** [comment]
> Ok, it is just the text ? It should still be working by copy/pasting my Client Key ?

Yes. It's just the text error. We tested with AWS's mqtt broker with all certificates and private key. It works well.

You upgraded gateway from old firmware v1.2.x right? Please try to restart your gateway and save all certificates again.

**Comment by gboolt** [comment]
Ok I am trying with Azure IoT Hub certificates, should not be different I guess ?

Yes I upgraded and restarted the Gateway. 
Actually, I tried to upgrade a new time with my last config tool version and now my Gateway Firmware Version is : 1.4.12 and it seems to be keeping the private key after saving now !

.. but still not seems to work, the device still has a disconnected status on my Azure IoT Explorer.

**Comment by volca** [comment]
We haven't tested with Azure IoT Hub yet. try your self-signed certificates first?

**Comment by gboolt** [comment]
I tried them using MQTTBox et MQTT.fx clients and they were working fine. 
Is the client-id constrained (I see ClientID=PREFIX+MAC_GATEWAY in the config tool) ?

**Comment by volca** [comment]
Does Azure IoT Hub constrain the client ID?

**Comment by gboolt** [comment]
Yes I think so, it has to be the name of the device defined in Azure IoT Hub. 
I entered the name of my device in the Gateway config but if the gateway Config change the Client-Id I potentially have to align the name in my Azure IoT Hub.
![image](https://user-images.githubusercontent.com/43132835/110303066-3d2f6580-7ffa-11eb-8b1e-48b0b8baa63c.png)

For example here, the real client-id is **gtw1+MAC_ADRESS** ?

**Comment by volca** [comment]
Please append `$$$` to the end to remove the suffix.

e.g.

* change Client ID Prefix = `gtw1$$$`
* real Client ID = `gtw1`

**Comment by gboolt** [comment]
I tried with $$$, still disconnected status :/ 

![image](https://user-images.githubusercontent.com/43132835/110306365-08bda880-7ffe-11eb-80c1-af21d6631c39.png)

Does the Gateway support TLSv1.2 version ?

**Comment by gboolt** [comment]
Also, does the gateway support MQTT v3.1.1 ?

**Comment by volca** [comment]
Could you please send all certificates and MQTT host, username and password etc to  my email? I will check it at my end tomorrow.

**Comment by gboolt** [comment]
I will check if I can do that. Not sure I am allowed to do so :/ . 

- Is there a way to have some logs from the gateway ? with Connecting events / Disconnecting events etc. ?

**Comment by volca** [comment]
I will reply you by email instead.

**Comment by gboolt** [comment]
fixed with the 1.4.13 firmware version. thanks.

**Comment by volca** [comment]
note: here's [the wiki for How to configure gateway for Azure IoT Hub](https://wiki.aprbrother.com/en/FAQ_For_AB_BLE_Gateway_V4.html#q-how-to-configure-gateway-to-work-with-azure-iot-hub)
